---
- name: Configure bridge
  community.routeros.command:
    commands:
      - /interface bridge add name={{ routerboard_bridge_interface_name }}
  register: bridge_result

- name: Debug bridge configuration result
  ansible.builtin.debug:
    var: bridge_result

- name: Add all ethernet ports to bridge
  community.routeros.command:
    commands:
      - /interface bridge port add bridge={{ routerboard_bridge_interface_name }} interface=ether{{ item }}
  loop:
    - 1
    - 2
    - 3
    - 4
    - 5
  register: bridge_ports_result

- name: Debug bridge ports addition result
  ansible.builtin.debug:
    var: bridge_ports_result
