---
- name: Check SSH connectivity
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    timeout: 10
  delegate_to: localhost
  ignore_errors: true
  register: ssh_check

- name: Check API connectivity
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    port: 8728
    timeout: 10
  delegate_to: localhost
  ignore_errors: true
  register: api_check

- name: Display service status
  ansible.builtin.debug:
    msg:
      - "SSH Status: {{ 'Available' if ssh_check.failed == false else 'Not Available' }}"
      - "API Status: {{ 'Available' if api_check.failed == false else 'Not Available' }}"

- name: Fail if SSH is not available
  ansible.builtin.fail:
    msg: "SSH service is not available on the RouterBoard"
  when: ssh_check.failed

- name: Wait for RouterBoard to be accessible
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    timeout: 300
  delegate_to: localhost

- name: Check configuration mode
  community.routeros.command:
    commands:
      - /system routerboard print
  register: config_mode_check


- name: Display configuration mode
  ansible.builtin.debug:
    msg: "Configuration Mode: {{ config_mode_check.stdout }}"
